spring:
  application:
    name:ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen3-max
        api-key: ${DASHSCOPE_API_KEY}
      embedding-model:
        model-name: text-embedding-v4
        api-key: ${DASHSCOPE_API_KEY}
      streaming-chat-model:
        model-name: qwen-max
        api-key: ${DASHSCOPE_API_KEY}
bigmodel:
  api-key: ${BIGMODEL_API_KEY}
server:
  port: 8081
  servlet:
    context-path: /api